---
  - name: check nodejs is installed
    command: /usr/bin/node -v
    register: node_installed
    ignore_errors: true
    changed_when: False


  - name: node install
    yum:
        name: "nodejs"
        state: absent
    become: yes

  - name: install nodejs 10.13.0
    shell: rpm -Uvh https://rpm.nodesource.com//pub_10.x/el/6/x86_64/nodejs-10.13.0-1nodesource.x86_64.rpm
    become: yes


  # - name: execute nodejs setup script
  #   shell: /tmp/node_setup.sh
  #   when: node_installed is failed
  #   become: yes
  
  - name: node install
    yum:
      name: "nodejs"
      state: latest
    become: yes
  
  - name: add yarn repository
    get_url:
      url: https://dl.yarnpkg.com/rpm/yarn.repo
      dest: /etc/yum.repos.d/yarn.repo
    become: yes
  
  - name: yum install
    yum:
      name: "yarn"
      state: latest
    become: yes
